### ISSUE TITLE
css zip corrupted

### ISSUE THREAD

**Issue by glasgowm148** [Neoteroi/mkdocs-plugins#21] opened 2022-10-25 10:00 UTC
```
Archive:  css-v0.1.2 (1).zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of css-v0.1.2 (1).zip or
        css-v0.1.2 (1).zip.zip, and cannot find css-v0.1.2 (1).zip.ZIP, period.
```

**Comment by glasgowm148** [comment] 2022-10-25 10:07
got working ones from here

https://github.com/Neoteroi/mkdocs-plugins/releases/tag/v0.0.6

**Comment by RobertoPrevato** [comment] 2022-10-25 10:14
Hi @glasgowm148 
Thanks for the heads up, I didn't notice the ZIP file was corrupted. They are built in the GitHub Actions and published as artifacts.

Weeks ago, I dedicated some time trying to publish them automatically as release files, but I had some issues and no time to correct that.

I don't recommend using old CSS files because they won't include rules for the new features (e.g. `contribs` plugin). It's best if you take the complete file from the documentation site, here:

https://www.neoteroi.dev/mkdocs-plugins/css/neoteroi.css

**Comment by RobertoPrevato** [comment] 2022-12-20 22:33
This is now fixed in the GitHub Workflows. It was caused by a wrong file extension configured in the action.

**Closed by RobertoPrevato** 2022-12-20 22:33 UTC
